### ISSUE TITLE
Meal Plan Page - New Meal Button

### ISSUE THREAD

**Issue by Dean110** [2019-Flexcode-Cohort/smart-shopping-list#43]
## User Story:
As a user,
when I click on the new meal button I want to be taken to the form to add a meal,
so that I can add a new meal to the application.

**Comment by Dean110** [comment]
## This card is considered done when:
- [x] Clicking on the "NEW MEAL" button takes you to the `/add-meal` endpoint.

**Comment by calebdsharp** [comment]
this is done

**Comment by Dean110** [comment]
Functionality exists as requested.
