### ISSUE TITLE
Meal Plan Page - Edit Meal Link

### ISSUE THREAD

**Issue by Dean110** [2019-Flexcode-Cohort/smart-shopping-list#45]
## User Story:
As a user,
when I click on the name of a meal I want to be directed to a page where I can edit that meals contents, 
so that I can make changes to an existing meal in a direct fashion.

**Comment by Dean110** [comment]
## This card is considered done when:
- [x] Clicking on the meals name takes you to an endpoint for editing the contents of a meal.

**Comment by calebdsharp** [comment]
this has been done

**Comment by Dean110** [comment]
Functionality exists as requested.
